version: '3.7'

services:
  api:
    restart: always
    tty: true
    build:
      context: .
      dockerfile: dockerfile
      target: prod
      args:
        port: ${PORT}
    environment:
      - GIN_MODE=release
    ports:
      - ${PORT}:${PORT}
    command: http
